# Generated by Django 3.2.5 on 2021-09-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_examen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='like',
        ),
        migrations.AddField(
            model_name='quote',
            name='like',
            field=models.ManyToManyField(related_name='likes', to='app_examen.User'),
        ),
    ]
